LowDataset:
  data_path: audio_files.jsonl
  dir_inputs: data/inputs
  dir_labels: data/labels
  stereo: False
  batch_size: 1
  masking: False
  max_duration: 90
  max_token_len: 7500
  codebook_size: 1027
  pad_token: 1025
  bos_toke: 1024
  eos_token: 1026
  codebook_num: 8

lr: 0.0001
epochs: 1
bandwidth: 6.0
stereo: False

Transformer:
  num_encoder_layers: 6
  num_decoder_layers: 6
  d_model: 128
  nhead: 4
  dropout: 0.1
  d_ff: 1024
