pad_token: &pad_token 1025
codebook_size: &codebook_size 1027
stereo: &stereo False
# Supported bandwidths are 1.5kbps (n_q = 2), 3 kbps (n_q = 4), 6 kbps (n_q = 8) 
# and 12 kbps (n_q =16) and 24kbps (n_q=32).
codebook_num: &codebook_num 8
bos_token: &bos_token 1024
eos_token: &eos_token 1026
max_len_token: &max_len_token 7500

LowDataset:
  data_path: audio_files.jsonl
  dir_inputs: data/inputs
  dir_labels: data/labels
  dir_midi: data/out
  stereo: *stereo
  masking: False
  max_duration: 90
  # Referenciar valores predeterminados
  bos_token: *bos_token
  eos_token: *eos_token
  pad_token: *pad_token

lr: 0.0001
epochs: 1
bandwidth: 6.0
batch_size: 1

Transformer:
  # Referenciar valores predeterminados
  pad_token: *pad_token
  codebook_size: *codebook_size
  codebook_num: *codebook_num
  num_encoder_layers: 6
  num_decoder_layers: 6
  d_model: 128
  nhead: 4
  dropout: 0.1
  d_ff: 1024
  flash: True
  max_len_token: *max_len_token
  max_len_midi: 13148

TokenizerConfig:
  pitch_range: [21, 109]
  beat_res: {0-4: 8, 4-12: 4}
  num_velocities: 32
  special_tokens: [PAD, BOS, EOS, MASK]
  use_chords: true
  use_rests: false
  use_tempos: true
  use_time_signatures: false
  use_programs: false
  num_tempos: 32
  tempo_range: [40, 250]
