pad_token: &pad_token 1025
codebook_size: &codebook_size 1027
stereo: &stereo False
# Supported bandwidths are 1.5kbps (n_q = 2), 3 kbps (n_q = 4), 6 kbps (n_q = 8) 
# and 12 kbps (n_q =16) and 24kbps (n_q=32).
codebook_num: &codebook_num 8
bos_token: &bos_token 1024
eos_token: &eos_token 1026
max_len_token: &max_len_token 21000

LowDataset:
  dir_labels: data/lowdata
  dir_midi: data/lowmidi
  stereo: *stereo
  masking: False
  # Referenciar valores predeterminados
  bos_token: *bos_token
  eos_token: *eos_token
  pad_token: *pad_token

lr: 0.01
epochs: 50
bandwidth: 6.0
batch_size: 2
output_dir: model_output
sliding_window: 5000

Transformer:
  # Referenciar valores predeterminados
  pad_token: *pad_token
  codebook_size: *codebook_size
  codebook_num: *codebook_num
  num_encoder_layers: 6
  num_decoder_layers: 6
  d_model: 512
  nhead: 8
  dropout: 0.1
  d_ff: 2048
  flash: True
  max_len_token: *max_len_token
  max_len_midi: 13148
